apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: 085210251746.dkr.ecr.us-east-1.amazonaws.com/docker-image
          imagePullPolicy: Always
          name: dockerimg
          ports:
            - containerPort: 3000
