apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: public.ecr.aws/u0m9v3a3/docker-image-1
          imagePullPolicy: Always
          name: dockerimg
          ports:
            - containerPort: 3000
