apiVersion: v1
kind: Secret
metadata:
name: my-registry-key
data:
.dockerconfigjson: ewoJImF1dGhzIjogewoJCSIwODUyMTAyNTE3NDYuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsVlJ6QTBXbGhL
U1ZVeGEzaFZNVnBGVlVVMGQwMHlhRXRWUlZadlkxUnJkbEZZUm5wWFdFRTFZMVJPVGs5R1JrMWxW
MmhDVkVSS1RrNHlSazFoVlhSelZURk9lbFZET1UxV2EzQjNZa2RvYldReWJ6Rldha1l6Vm5wYWJF
c3pVbTlPUkdSSFkxVk5kbE5XVFhaUFYxWndUV3hDTkdNeGIzSlJla3BaVXpCT2VsSXhjRTFTVm5C
eFlrVlNXbUl4YnpCU01FNTZXakZzYWxFd2NIUmtiVVpLVm5wQ2NWa3ljSEJpTTJ4NVdWWndSbVJW
Y0c5VU1VcHlVbTVLVEZOVVRrUmtSWEJ1V2tka1QxZHJTbWhUVkVwcFpGaHdlazVXYXpGa1YwcHlZ
MFJTVVdKNlVuZFNlbHBhVDBSV1NVMVdjSFJOVld4U1pWUkdjMlZXVFhaVFZrSlVaRlZPWVdOV1p6
TmFiVEV6VFZjMWRGUjZSakZUVjNoeFZIcFNTMDR5ZEVoaVIzUkxaR3h3YlZrd1VuRlhWbFYyVkVk
T2NHSjVkRkZsVjA1WFZFWmFkMVl4V1hwUk1rcFlVa2RGTldSSWFGQmFSa2t3VFVjeFYyRlljREZh
Vm1Sb1l6QXhSRkZyT1RaalNHZ3hZbGhvVWxSc1NqSlZiRXBWVGxVNVNGcEhNWHBhVkdoelVUTk9S
V1I1ZEVaUlZVcFZWRlZyY2xkWVpGcFRiR1IxVGpCNE1WUkdhRUprUjAxM1ZESlZkbHBVWTNkTmEw
cHRXbXhhTTFreVdsQk9SV2h6V214S1dHTnNaSGRXYlhCeVRWZFJjbUpzUlhwYVZURjVWMGRaTVZO
WGVGRmlNREZQVkRCYWJGUnJkRlZoTW14WVZuazVTMk5wZEZWVk1uaDJZMVphVVU1dVpEUk1lbVJh
VTBSYU5WWnJiM3BTVmtKUlVqSXdkbEl6UmtoT1ZUaDVUMWhvUzFkVWFGQlBSazV3VFVod1lVOUdU
bGhqV0ZaVFdqQndiazlVV2paUk1sb3lWVzB4YkZwdFNuQlRNR1JSVGxWRmNsWlVWbGxPTTBvd1l6
RkNjMkY2VFROYVJFSlpaVzVPVmxsVVVsTlRhbFpMWVVoS2ExTlhjelZaVjFaR1ltcGFNMUV4YUVo
TlZsSTFUMGh3TWxVeFZuUmlWMHBQWkRCR1VHSkVVazFsYmxaelRrUldlV1ZVYkUxbFNHOTVZVWhz
VjA5RVkzaFJNRlV4VkZSYWQxbFZhRXRQUlRGdFVsUnJkMkZyZEhoamFrb3lWbFZ3UjJWSVZqRk5N
azVGV2xoU1ZFd3hiR2xqVldzelZWUnNSRTFWZDNKaVF6bHJWbGQwY0dOR1pIWmxRemxZWW14RmQw
MUZSalZoYldSWVZXNUNTV0ZHV1RCYVNFVXhWRVV4U2s5RVRreGFNR1JHVWtoWk1tSkZPSGhqTURC
MlRXeG9hRkpYTURWV1NGbDNZMGRLYjJGVVFtaGxiVkp5V1ZaR1ZWWnRVakJPV0ZwcFRXczRlRkV6
Um5SaFYyc3hVVlZ3V1U1ck9VSlNiRnBYVDBoYWVVNXVRbUZSV0ZreVdrWndXRXd6YUhSVE1HeFZU
MVU1UTFKNldsbFNia1pTVlc1c2IySlhjREJoTTFKSVl6Rm5NMWR0ZUhobGFrWlRZMjVvVW1GRE9V
eFRVemxHWVZobmRtRnVaSFpUVkZKeFYycGpjbUY2Um05TE0ydDZaVzVrVGxOWFVuUmlWemwxV1Za
R1JWZEdaRzFYU0VwMVVWWlJlbVZXV1RWU1dHaFlWSHBXTTFONlVrMVdhMVpwVW10c2IyVkhTakZW
TVUxM1MzcFdiR1JYZUZoWlYwWnJUMGQzTTFOR1ZYSmhWV3MwVFRCMFVGRnVWbGRrVlRsMVpVWm9j
MlZGTURKa01VcFJZVVZvV21OWVVuWlhhM2h4VWpCa1JHTnJOSFpUVlRWUlYxWmFWV0ZJWkVSaWJr
STFXV3RrYkUxdVRYWk9TRTVoVGtScmRsbHBkRzVUUkVFd1ZGaFNRazVVWkRGTE1IUlVXVEEwY2s1
RlRsUlhibVJJV214d1VXRnRNVXhTYWtvd1ZGUkdWbVJWTUhsaU0wSlNZVVZ3TWxkdFRtMVNNVm96
Wkd0MGNWSlZSVEJqU0VKTlpWaFZjbVF4YkZCaFF6azBaRlJrTW1JeFVUTmtia3BRVFZWNFUyRnBk
RkJPTWxZellqRmtkV0pJUm5OV1NGVjVaVmhrV0ZrelpFdFRWVTVXVFhwb2FtRnFiR2hVVnpCeVRV
Um5lVXN4VmxGa1Z6VnVWRE5TYUZWdGVIbGpiVVY2VjBjeGFGRXhiREpPYTFaR1UxUk9TVTV0VWxo
V1IxSkdWMVZXUmsxV1FYWlZWa0pWVjFSS2JsSXpRbkJTVkdob1pGWndXRlZyZUZkalJGcE9WRzVD
VTFVelVqQmtSelY2VlZkc1RGWjZSWHBWVm1kMllrUmtkVmw2Vlhsa1ZVNVlXVzF3V1dGSFZuZFhS
a1o1VFZkNFRWVkljR3RaV0VZeVpVYzVTVkY2VG5wVVdHeHdXWGs1TmxWRlVuZE9XRkV3UzNwR2VG
VnRhRUpNTVd4VVRsTTVObEZ1VWtKWmExRTFWRU01VFZadWJESlplbHBhWTFWR1dGbDZWbTFsUjJO
M1lVZG9hVTVzUmtST1JUVkpXbGQwU2xWcVJqVlNNa2t5V1RCT2NWSlZiRXRUYkhCdlVqTnNRMUV3
UlRSaE1IUTBUbFpGZUdOV1dsZE9RM1JxVERCd1ZGSnVSblZVZWxwclRuazVjVlpYVVhwV1dHeFBU
WHBhUkdKNlNsaGpiVlpXWkZWT05XTkhXbFpSYTJoTllXMUdTMDFGVm5oaWJURTFXbGRTV1ZWRlNt
RlViV3d5VVd0a01tUnVSbXhXUnpCM1RrZGFkV1ZIT1ZOa1IzY3dWVWhSTkdWRVJtcGhSRTQwWVhw
TmVrNUViR2xoVldoRVZsUmFTazF0YkhOa1IwNUNZMWh3YjFFeVVrdFBSRTEzVWpOd1ZsbFdZelZh
YTBwWlRESktVRm94Y0VKTldGcHlaRVJDY1UxWVVucFRWVGxwWlcwMVdWcHRlR2hTUjNSV1lWZGFU
azR4U2xaU2FYUkxaR3hrV0U5RWJGQmpNRFV5WTBWa1VtSkZaR3RTTUU1WlZESmFUVmt6V21saVZt
UjBWWGs1ZUUwd1VuQmxSWEExV210a1MxRXdVbEJVVlVaMVkwZGFiMk5WT1d4V2JVbHlZMnR3VDFO
clpHOWlNblJ0V2pOQ2VHTlhZek5aVmtwRlpGUk9iazVIVWxGUlZFazBVekpTV21OdVJrSlVia1pH
VDBWd1VVMUdaRzFrYkd0eVZVUm9kbGx0V1RSUlZrSjJWVlJrVlZWRWJFVk9iV2cxVTI1YWFGVkVX
bXBWYlVac1RVVnNhbFZFYkdsVFNFSkpVakJXVVZvd09VOWFNbHBNVTBad2NsSnJTbEpPVld4V1ZU
RldlbE50T1ZWVGFsa3lZekZvZG1Oc2FGVlpWbEpTV20xRmVtSnJXbE5OTVVaQ1UwZEtWRkpzUmxo
TmVUbFpaVWhyTWxKRWFFeFhSV3R5U3pKak5GRlhjSFJVZWtGMllqQktiR1F3UmsxTlZGVjZaRmhH
ZG1NeFFsaGhlbWhXVFVkYWRFNHhWbTVQVkVZeldtMVpkazVYZUZKWldGWkVUMFp3VTJKNlVsbGlV
M1F4VmtSUmRsbFZUbXRTU0VaYVpVVTFURmRJVG5oYWJtczBUbFZaTVZkR1p6VlphMFl6WVd0NFYx
cFVhR3RWUjFKMFlrWkdjMlI2TURsSmFYZHBXa2RHTUZsWGRHeGxVMGsyU1d0R1VsSlZTa0pUUjJn
ellsUkNXbGxWYkZSVGJWWlRaRVZ3ZEU1WE5IaFNlbG94WTFkV2JHRXhhREZpTVdoWlZVZFZNVlpW
V21wYVZHeFRZMVJuZGsxVVVqTlJWVVpDVTBSU00xcHJSbHBUYTNSMlYydHNiMlJ0VGs5UlZrWnFV
akk1U0U5SVpHbFZWV3hEVVZWU1EySXdTbTVoTTBadllUSnNTRTlZWTNkUmEwb3pVbGhrU1ZveGJF
dFhWV3hoVTFWR1dGWlZVa05SVlZZeFZGVktSbEpWVWt4V2Vtc3dUVVV4YTAxSGVIQlNNSEJTVW10
T2NWb3diRU5TVld4Q1RqTm5NV0ZET1d4V1JVcFNVa2hhUkdSWVduVlhWbkJxWTI1WmQxUnRXbEZS
TUVvMFZsUkdXR05VVWpWWFZVWnhVV3RuTkZaR2JHdFRSVTB3U3pGb1JWUldRalpQVjFrMVpERmpl
RkpYT1U5UFJsbzBXVlpLTkdGSWFHRmxiRmw1V2pGR1MxcHFiRWxTVldzNVNXbDNhV1J0Vm5sak1t
eDJZbWxKTmtscVNXbE1RMG93WlZoQ2JFbHFiMmxTUlVaVlVWWTVURkpXYTJsTVEwcHNaVWhDY0dO
dFJqQmhWemwxU1dwdmVFNXFVVEJPZWtWNlRYcHJlR1pSUFQwPSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
